// This file is auto-generated by Supabase CLI
// For now, we'll define basic types manually
// In production, run: npx supabase gen types typescript --project-id YOUR_PROJECT_ID > src/lib/database.types.ts

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          username: string
          avatar_url: string | null
          created_at: string
        }
        Insert: {
          id: string
          username: string
          avatar_url?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          username?: string
          avatar_url?: string | null
          created_at?: string
        }
      }
      notes: {
        Row: {
          id: string
          user_id: string
          x: number
          y: number
          z: number
          text: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          x: number
          y: number
          z: number
          text: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          x?: number
          y?: number
          z?: number
          text?: string
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}

